### ISSUE TITLE
如何搭建起来

### ISSUE THREAD

**Issue by vicar5235** [whexy/blog-1999#129]
你好，很喜欢这套博客的风格，但我没有代码知识，请问我该如何将他运行起来呢？我想托管在 vercel 上，期待你的回复

**Comment by whexy** [comment]
非常感谢您的关注和支持！这个博客系统实际上是一个范例，旨在展示技术实现和设计理念，并非直接为普通用户提供可用产品。它可能更适合具备一定前端工作经验的用户去参考和修改，对于没有相关经验的用户，可能在部署和使用上会遇到一些挑战。希望您能够理解这一点。如果您对其他方面有兴趣或有其他需求，我也会非常乐意提供帮助。
